{% set name = "pandarallel" %}
{% set version = "1.6.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pandarallel-{{ version }}.tar.gz
  sha256: ad68d44dd70d015fa9cc27881b821d8b23697c62dff7e83aa30d616c050ffbb3

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - dill >=0.3.1
    - python >=3.6
    - pandas >=1
    - psutil

test:
  imports:
    - pandarallel
    - pandarallel.data_types
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/nalepae/pandarallel
  summary: An easy to use library to speed up computation (by parallelizing on multi CPUs) with pandas.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hadim
