{% set name = "pandarallel" %}
{% set version = "1.6.5" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pandarallel-{{ version }}.tar.gz
  sha256: 1c2df98ff6441e8ae13ff428ceebaa7ec42d731f7f972c41ce4fdef1d3adf640

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - dill >=0.3.1
    - python >={{ python_min }}
    - pandas >=1
    - psutil

test:
  imports:
    - pandarallel
    - pandarallel.data_types
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/nalepae/pandarallel
  summary: An easy to use library to speed up computation (by parallelizing on multi CPUs) with pandas.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
